global:
  application_name: :app_name:
  default_ec2_keyname: null
  default_platform: PHP
  default_region: null
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: git
  workspace_type: Application
